### ISSUE TITLE
Sometime under Windows I got NPE

### ISSUE THREAD

**Issue by rychkov** [the-mad-dog/rjc#1]
I run "Using connection pool" example with https://github.com/dmajkic/redis (redis-2.1.5-win32.zip) and got

Exception in thread "Thread-45" io.redis.rjc.RedisException: Cannot get a connection
    at io.redis.rjc.ds.PoolableDataSource.getConnection(PoolableDataSource.java:45)
    at io.redis.rjc.RedisNode.execute(RedisNode.java:59)
    at io.redis.rjc.RedisNode.set(RedisNode.java:84)
    at TestRedis$1.run(TestRedis.java:42)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.NullPointerException
    at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1158)
    at io.redis.rjc.ds.PoolableDataSource.getConnection(PoolableDataSource.java:43)
    ... 4 more
Exception in thread "Thread-47" io.redis.rjc.RedisException: Cannot get a connection
    at io.redis.rjc.ds.PoolableDataSource.getConnection(PoolableDataSource.java:45)
    at io.redis.rjc.RedisNode.execute(RedisNode.java:59)
    at io.redis.rjc.RedisNode.set(RedisNode.java:84)
    at TestRedis$1.run(TestRedis.java:42)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.NullPointerException
    at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1158)
    at io.redis.rjc.ds.PoolableDataSource.getConnection(PoolableDataSource.java:43)
    ... 4 more

**Comment by the-mad-dog** [comment]
fixed in 0.5.1
