### ISSUE TITLE
ERR wrong number of arguments for brpop command

### ISSUE THREAD

**Issue by jencompgeek** [the-mad-dog/rjc#18]
The following code throws the following Exception:

```
@Before
public void setUp() {
    SimpleDataSource dataSource = new SimpleDataSource("localhost", Protocol.DEFAULT_PORT, Protocol.DEFAULT_TIMEOUT, null);
    connection = dataSource.getConnection();
    client = new Client(connection);
}

@Test
public void testBrPop() {
    client.rpush("rpoplist", "foo");
    client.brpop("rpoplist");
    client.getAll();
}
```

Error:

```
org.idevlab.rjc.RedisException: ERR wrong number of arguments for 'brpop' command
at org.idevlab.rjc.protocol.Protocol.processError(Protocol.java:69)
at org.idevlab.rjc.protocol.Protocol.process(Protocol.java:76)
at org.idevlab.rjc.protocol.Protocol.read(Protocol.java:137)
at org.idevlab.rjc.ds.RedisConnectionImpl.getAll(RedisConnectionImpl.java:178)
at org.idevlab.rjc.Client.getAll(Client.java:696)
at org.springframework.data.redis.connection.rjc.RjcTest.testBrPop(RjcTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

**Comment by JensRantil** [comment]
I can recreate this bug also when using `[]byte` method:

```java
final byte[] QUEUE_NAME = "my-queue-name".getBytes(Charsets.UTF_8);
redis.brpop(QUEUE_NAME);
```

**Comment by JensRantil** [comment]
Sorry, ignore my previous comment. I added it to the wrong project :-/
